spring:
  profiles:
    active: ${PROFILE:test}
  application:
      name: eacharts-sample

server:
  port: ${ECHARTS_PORT:8000}
  
logging:
  pattern:
    console: '%n %d{HH:mm:ss} | %highlight(%-5level) | %cyan(%logger{30}) | %msg'
  level:
    root: INFO
    org:
      springframework: warn
      boot: error
