spring:
  main:
    lazy-initialization: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT}/${DB_DATABASE:example}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      max-lifetime: 1500000
      idle-timeout: 300000
      connection-timeout: 30000
      minimum-idle: 10
      maximum-pool-size: 200
      pool-name: "echarts-sample-pool"
      initialization-fail-timeout: -1
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
  jta:
    enabled: false

security:
  front:
    https-only: ${HTTPS_ONLY:false}
    csrf: ${CSRF_ENABLED:false}

application:
  size:
    page: ${PAGE_SIZE:20}

settings:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:4200}
    max-age: ${CORS_TIME:3600}
